Repository Moviles-2025-20/Swifties, pull requests merged in 2025-10, with the labels that each got.

#19 Feat/Authentication with Google
  GoogleService-Info.plist
  Swifties.xcodeproj/project.pbxproj
  Swifties.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swifties.xcodeproj/xcshareddata/xcschemes/Swifties.xcscheme
  Swifties/Assets.xcassets/Google.imageset/Contents.json
  Swifties/Assets.xcassets/Google.imageset/logo_googleg_color_3x_ios_29dp-transparent.png
  Swifties/Info.plist
  Swifties/Models/AuthUserModel.swift
  Swifties/Models/UserModelAuth.swift
  Swifties/Services/AuthService.swift
  Swifties/SwiftiesApp.swift
  Swifties/ViewModels/AuthViewModel.swift
  Swifties/Views/EventsListView.swift
  Swifties/Views/HomeView.swift
  Swifties/Views/LoadingView.swift
  Swifties/Views/LoginView.swift
  Swifties/Views/OnboardingView.swift
  Swifties/Views/StartView.swift
Labels: enhancement

#35 Minor changes and fixes
  Swifties/Views/ProfileView.swift
  Swifties/Views/StartView.swift
Labels: bug

#43 Weekly challenge
  Swifties/MainView.swift
  Swifties/SwiftiesApp.swift
  Swifties/Views/ActivityCompletion.swift
  Swifties/Views/HomeView.swift
  Swifties/Views/WishMeLuck.swift
Labels: enhancement

#46 twitter and navigation
  Swifties.xcodeproj/project.pbxproj
  Swifties/Services/AuthService.swift
  Swifties/ViewModels/AuthViewModel.swift
  Swifties/Views/LoginView.swift
Labels: enhancement

#52 Email login
  Swifties.xcodeproj/project.pbxproj
  Swifties/Models/UserAuthModel.swift
  Swifties/Services/AuthService.swift
  Swifties/SwiftiesApp.swift
  Swifties/ViewModels/AuthViewModel.swift
  Swifties/Views/LoginView.swift
  Swifties/Views/VerifyEmailView.swift
Labels: enhancement

#51 Added support for map view using Google Maps or Apple Maps (and fixes)
  Swifties/Info.plist
  Swifties/Services/EventNotificationService.swift
  Swifties/Services/LocationManager.swift
  Swifties/ViewModels/RegisterViewModel.swift
  Swifties/Views/ActivityCompletion.swift
  Swifties/Views/EventListView.swift
  Swifties/Views/EventMapView.swift
  Swifties/Views/HomeView.swift
  Swifties/Views/ProfileView.swift
Labels: enhancement

#55 changes
  Swifties/Components/Events/EventInfo.swift
  Swifties/Models/Event.swift
  Swifties/Models/UserModel.swift
  Swifties/ViewModels/EventDetailViewModel.swift
  Swifties/ViewModels/EventListViewModel.swift
  Swifties/ViewModels/ProfileViewModel.swift
  Swifties/Views/EventDetailView.swift
  Swifties/Views/EventListView.swift
  Swifties/Views/HomeView.swift
  Swifties/Views/UserInfoView.swift
  Swifties/Views/WishMeLuck.swift
Labels: enhancement

#56 Fixes to the bugs that had appeared
  Swifties/Models/Event.swift
  Swifties/Views/EventDetailView.swift
  Swifties/Views/EventListView.swift
  Swifties/Views/EventMapView.swift
  Swifties/Views/UserInfoView.swift
  Swifties/Views/WishMeLuck.swift
Labels: bug

#53 Comments view to be able to upload photos
  Swifties/Info.plist
  Swifties/Models/Comment.swift
  Swifties/Services/ImagePicker.swift
  Swifties/ViewModels/CommentViewModel.swift
  Swifties/Views/AddCommentView.swift
  Swifties/Views/EventDetailView.swift
Labels: enhancement

#57 Recommendations initialization
  Swifties/ViewModels/EventListViewModel.swift
  Swifties/ViewModels/HomeViewModel.swift
  Swifties/Views/HomeView.swift
Labels: enhancement

#60 Feat/wish me luck functionality
  Swifties/Components/TabBar/CustomTabBar.swift
  Swifties/MainView.swift
  Swifties/Models/UserActivity.swift
  Swifties/Models/WishMeLuckEvent.swift
  Swifties/ViewModels/WishMeLuckViewModel.swift
  Swifties/Views/HomeView.swift
  Swifties/Views/WeeklyChallengeView.swift
  Swifties/Views/WishMeLuck.swift
Labels: enhancement

#61 Revert "Feat/wish me luck functionality" Copilot issue
  Swifties/Components/TabBar/CustomTabBar.swift
  Swifties/MainView.swift
  Swifties/Models/UserActivity.swift
  Swifties/Models/WishMeLuckEvent.swift
  Swifties/ViewModels/WishMeLuckViewModel.swift
  Swifties/Views/HomeView.swift
  Swifties/Views/WeeklyChallengeView.swift
  Swifties/Views/WishMeLuck.swift
Labels: bug

#64 Comments bug fixing
  Swifties/ViewModels/CommentViewModel.swift
  Swifties/ViewModels/HomeViewModel.swift
Labels: bug

#65 Plis work
  Swifties/MainView.swift
  Swifties/Models/WishMeLuckEvent.swift
  Swifties/ViewModels/WishMeLuckViewModel.swift
  Swifties/Views/HomeView.swift
  Swifties/Views/WishMeLuck.swift
Labels: bug

#67 Buttons fixed
  Swifties/Views/EventDetailView.swift
  Swifties/Views/WeeklyChallengeView.swift
Labels: enhancement

#69 Wish me luck recommendation done
  Swifties/ViewModels/EventDetailViewModel.swift
  Swifties/ViewModels/WishMeLuckViewModel.swift
  Swifties/Views/EventDetailView.swift
  Swifties/Views/EventListView.swift
  Swifties/Views/WishMeLuck.swift
Labels: enhancement

#77 improve modularity
  Swifties/Models/FreeTimeSlot.swift
  Swifties/Models/WeeklyChallengeChartData.swift
  Swifties/ViewModels/UserInfoViewModel.swift
  Swifties/ViewModels/WeeklyChallengeViewModel.swift
  Swifties/Views/UserInfoView.swift
  Swifties/Views/WeeklyChallengeView.swift
Labels: enhancement

#78 Fixes to various bugs
  Swifties/Models/WishMeLuckEvent.swift
  Swifties/SwiftiesApp.swift
  Swifties/ViewModels/EventDetailViewModel.swift
  Swifties/ViewModels/EventListViewModel.swift
  Swifties/ViewModels/HomeViewModel.swift
  Swifties/Views/AddCommentView.swift
  Swifties/Views/EventDetailView.swift
  Swifties/Views/HomeView.swift
  Swifties/Views/LoginView.swift
  Swifties/Views/ProfileView.swift
  Swifties/Views/RegisterView.swift
Labels: bug

#81 Fixing the issues made by previous commit
  Swifties/ViewModels/HomeViewModel.swift
Labels: bug, enhancement

#83 Analitics service
  Swifties.xcodeproj/project.pbxproj
  Swifties/AnalyticsService.swift
  Swifties/Services/CrashlyticsService.swift
  Swifties/SwiftiesApp.swift
  Swifties/ViewModels/RegisterViewModel.swift
  Swifties/ViewModels/WeeklyChallengeViewModel.swift
  Swifties/Views/EventDetailView.swift
  Swifties/Views/EventListView.swift
  Swifties/Views/HomeView.swift
  Swifties/Views/WishMeLuck.swift
Labels: enhancement

#98 Fix Bug of solitary event
  Swifties/Components/Events/FilterToggle.swift
  Swifties/Components/Factories/EventFactory.swift
  Swifties/Views/EventMapView.swift
  Swifties/Views/HomeView.swift
Labels: bug, enhancement
